# Generated by Django 5.0.1 on 2025-02-19 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bibleverse'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='bibleverse',
            old_name='verse',
            new_name='verse_number',
        ),
        migrations.RemoveField(
            model_name='bibleverse',
            name='book',
        ),
        migrations.CreateModel(
            name='BibleChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.biblebook')),
            ],
        ),
        migrations.AlterField(
            model_name='bibleverse',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.biblechapter'),
        ),
    ]
