# Generated by Django 5.0.1 on 2025-02-26 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, related_name='authorized_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, related_name='authorized_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
